### ISSUE TITLE
How is the dataset used for multi-modal anomaly detection?

### ISSUE THREAD

**Issue by yuanzhao-CVLAB** [M-3LAB/Real3D-AD#10]
Could you provide a colored point cloud that can be conveniently transformed into depth and RGB images? Alternatively, could you suggest a method to transform this dataset to meet the requirements for multi-modal anomaly detection?

**Comment by jiaq-liu** [comment]
> zhaoyuan1209

It's not easy to provide this dataset extra color. If you use other tools to colorize, it is recommended to color the point cloud first and then map it to the 2D plane. But this is also not easy, and may even be more difficult than creating a synthetic RGB point cloud dataset.

**Comment by yuanzhao-CVLAB** [comment]
So, this dataset cannot be used to evaluate multi-modal anomaly detection tasks? (RGB+Depth image)

**Comment by jiaq-liu** [comment]
> So, this dataset cannot be used to evaluate multi-modal anomaly detection tasks? (RGB+Depth image)

The dataset cannot be used to evaluate multi-modal anomaly detection tasks. The point clouds in the dataset have no colors.
