### ISSUE TITLE
Where is equation 7?

### ISSUE THREAD

**Issue by linlinge** [M-3LAB/Real3D-AD#11]
While reading the code, I found that in the function ```compute_s_s_map```  in ```pc_features.py```, the author claims that the code corresponds to Equation 7 in the paper. However, I couldn't locate this equation in the paper. The relevant code is shown below:

```python
# reweighting
m_test = patch[s_idx].unsqueeze(0)  # anomalous patch
m_star = cur_patch_lib[min_idx[s_idx]].unsqueeze(0)  # closest neighbour
w_dist = torch.cdist(m_star, cur_patch_lib)  # find knn to m_star pt.1
_, nn_idx = torch.topk(w_dist, k=self.n_reweight, largest=False)  # pt.2
# equation 7 from the paper                                                                                                                 * here
m_star_knn = torch.linalg.norm(m_test - cur_patch_lib[nn_idx[0, 1:]], dim=1)
# Softmax normalization trick as in transformers.
# As the patch vectors grow larger, their norm might differ a lot.
# exp(norm) can give infinities.
D = torch.sqrt(torch.tensor(patch.shape[1]))
w = 1 - (torch.exp(s_star / D) / (torch.sum(torch.exp(m_star_knn / D))))
s = w * s_star
```

**Comment by jiaq-liu** [comment]
@linlinge  This part of the code is obtained from M3DM, so it refers to formula 7 in the M3DM paper (https://arxiv.org/abs/2303.00601). The reweighting approach is obtained from PatchCore, you can also refer to the PatchCore pape (https://arxiv.org/abs/2106.08265).

**Comment by linlinge** [comment]
Thank you very much!
