### ISSUE TITLE
复现结果存在较大误差（大于0.1）

### ISSUE THREAD

**Issue by Guangyun-Xu** [M-3LAB/Real3D-AD#12]
我通过运行指令`python3 main_reg3dad.py --gpu 0 --seed 42 --memory_size 10000 --anomaly_scorer_num_nn 1 --faiss_on_gpu --faiss_num_workers 8 sampler -p 0.1 approx_greedy_coreset`（start.sh中的最后一行）得到reg3dad的测试结果，其中有两个task与readme中的Object AUROC和Object AUPR结果差距较大，分别是candybar和chicken

下面是原始数据：

> Task:candybar, image_auc:0.726, pixel_auc:0.6850491800194194, image_ap:0.7320999599429406, pixel_ap:0.06516038909882592, time_cost:10.123863711357117
Task:chicken, image_auc:0.6552706552706552, pixel_auc:0.7403133167372637, image_ap:0.6247698227408676, pixel_ap:0.05462278892513155, time_cost:17.526476030079824

下面是对比表格：
| candybar | Object AUROC | Point AUROC | Object AUPR | Point AUPR |
| :------: | :----------: | :---------: | :---------: | ---------- |
|  readme  |    0.827     |    0.724    |    0.824    | 0.109      |
|   复现   |    0.726     |    0.685    |    0.732    | 0.065      |

| chicken | Object AUROC | Point AUROC | Object AUPR | Point AUPR |
| :-----: | :----------: | :---------: | :---------: | ---------- |
| readme  |    0.852     |    0.676    |    0.884    | 0.044      |
|  复现   |    0.655     |    0.740    |    0.625    | 0.055      |

我的开发环境是ubuntu20.04，cuda11.8，pytorch 2.4.1

**Comment by jiaq-liu** [comment]
@Guangyun-Xu 你好，实验环境为pytorch 1.8, cuda 11.3, 可能会导致结果不同。另外不同机器复现结果也会存在一定随机性。
