### ISSUE TITLE
显存问题

### ISSUE THREAD

**Issue by jun614** [M-3LAB/Real3D-AD#13]
请问3060 12g能训练这个网络吗，我运行了这两个命令能正常运行，当时另外几条命令都报错了。请问是显存的问题吗。谢谢
`python3 main_patchcore_fpfh.py --gpu 0 --seed 42 --memory_size 10000 --anomaly_scorer_num_nn 1 --faiss_on_gpu --faiss_num_workers 8 sampler -p 0.1 approx_greedy_coreset
python3 main_patchcore_fpfh_raw.py --gpu 0 --seed 42 --memory_size 10000 --anomaly_scorer_num_nn 1 --faiss_on_gpu --faiss_num_workers 8 sampler -p 0.1 `approx_greedy_coreset``

**Comment by jiaq-liu** [comment]
@jun614 同学你好，这两个的命令是用fpfh作为特征的，其他命令需要加载point transformer，12g不足以加载。默认的情况下需要占用40G的显存，此外在32G的V100上也是可以的，再低的话就没法加载了。可以考虑降低point transformer中的group_size和num_group，不过应该也需要20G左右的显存。
