### ISSUE TITLE
有没有predict的代码或者管道

### ISSUE THREAD

**Issue by ShuleHao** [M-3LAB/Real3D-AD#2]
单个pca文件的推理，以及显示

**Comment by shirowalker** [comment]
你好，现在暂时没有单独的推理代码。因为训练不涉及模型更新，单纯是将样本特征存储并推理，单独的推理速度提升并不多。如果需要推理代码的话，可以考虑将特征提前存储。

**Comment by ShuleHao** [comment]
可以把模型推理出来的进行可视化吗



---原始邮件---
发件人: "Jiaqi ***@***.***&gt;
发送时间: 2024年1月13日(周六) 下午3:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [M-3LAB/Real3D-AD] 有没有predict的代码或者管道 (Issue #2)




 
你好，现在暂时没有单独的推理代码。因为训练不涉及模型更新，单纯是将样本特征存储并推理，单独的推理速度提升并不多。如果需要推理代码的话，可以考虑将特征提前存储。

**Comment by shirowalker** [comment]
> 可以把模型推理出来的进行可视化吗
> […](#)
> ---原始邮件--- 发件人: "Jiaqi ***@***.***&gt; 发送时间: 2024年1月13日(周六) 下午3:29 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [M-3LAB/Real3D-AD] 有没有predict的代码或者管道 (Issue #2) 你好，现在暂时没有单独的推理代码。因为训练不涉及模型更新，单纯是将样本特征存储并推理，单独的推理速度提升并不多。如果需要推理代码的话，可以考虑将特征提前存储。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

可以的，utils/visualization.py 下有许多函数可以支持可视化。
比如vis_pointcloud_anomalymap_pcdpath(pcd_path, anomaly_map)就可以结合点云和anomaly map可视化。
