### ISSUE TITLE
What is the difference between the two dataset?

### ISSUE THREAD

**Issue by limaodaxia** [M-3LAB/Real3D-AD#3]
![image](https://github.com/M-3LAB/Real3D-AD/assets/68214694/1bf47caf-44f7-4350-83fe-aedd55ec6398)

-------------------------------------------------------------------------------------------
What is the difference between the two dataset shown in the picture above?

**Comment by jiaq-liu** [comment]
> ![image](https://private-user-images.githubusercontent.com/68214694/324631749-1bf47caf-44f7-4350-83fe-aedd55ec6398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MzgxMDUsIm5iZiI6MTcxMzgzNzgwNSwicGF0aCI6Ii82ODIxNDY5NC8zMjQ2MzE3NDktMWJmNDdjYWYtNDRmNy00MzUwLTgzZmUtYWVkZDU1ZWM2Mzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDAyMDMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMGEyYWViOGNkOTdmZTcwNzA1ZWEyMDkwNDY4MTNkN2Y5ZWE1NjcyYmNiNjNjMjYyNzk0NDY3YzUzZTY5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q7ogVmiZyyQ1O_JWZkfXaKtFhJTG5UDgrHyeaDpH5a8)
> 
> What is the difference between the two dataset shown in the picture above?

As you can see, one is in ply format and the other is in pcd format. Pcd only contains point coordinate information; Ply has more information, such as mesh. Commonly we only use pcd. You also can use ply files if you have any ideas.

**Comment by limaodaxia** [comment]
Thank you for your patient reply!
