### ISSUE TITLE
点云文件名参数含义

### ISSUE THREAD

**Issue by LFXT** [M-3LAB/Real3D-AD#4]
![gt](https://github.com/M-3LAB/Real3D-AD/assets/121942758/ee789534-04c3-4015-aee6-b4616aa403df)
请问一下，如图所示，文件名里面前缀数字以及部分文件cut是什么含义？

**Comment by shirowalker** [comment]
前缀数字是采集时候的编号。cut是对原有结果进行了裁剪，去除了不平整的边缘区域。

**Comment by jiaq-liu** [comment]
> ![gt](https://private-user-images.githubusercontent.com/121942758/327490570-ee789534-04c3-4015-aee6-b4616aa403df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjYwODEsIm5iZiI6MTcxNDY2NTc4MSwicGF0aCI6Ii8xMjE5NDI3NTgvMzI3NDkwNTcwLWVlNzg5NTM0LTA0YzMtNDAxNS1hZWU2LWI0NjE2YWE0MDNkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQxNjAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDZlZTgxNmE3MzM5NjRkMzAyOGIyYTYxMTUzNTY1Y2Y1OTY3NmVhNTkwM2MyYjliYjA5NDhiNmQ1NTFlMzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p8VTAd2K85aG4ndmaioWn7gtVBSTgdCMdB590nlKoDc) 请问一下，如图所示，文件名里面前缀数字以及部分文件cut是什么含义？

https://github.com/M-3LAB/Real3D-AD/issues/4#issue-2275840817
