### ISSUE TITLE
Is there a supplementary material for this paper, and how do I get it?

### ISSUE THREAD

**Issue by ZZZBBBZZZ** [M-3LAB/Real3D-AD#5]
I remember that NeuroIPS Track on Datasets and Benchmarks requires a supplementary material, which I think can help me better understand this dataset.

**Comment by jiaq-liu** [comment]
> I remember that NeuroIPS Track on Datasets and Benchmarks requires a supplementary material, which I think can help me better understand this dataset.

The supplementary material is the appendix of the paper.
