### ISSUE TITLE
关于异常的类型

### ISSUE THREAD

**Issue by Kkkwui** [M-3LAB/Real3D-AD#6]
你好！非常感谢你们提出了点云异常数据集。我有点问题想请教一下：1.我似乎并没有在数据集中看到文章中所说的incompleteness类型的异常，只有sink和bulge类型的异常？2.gt中带有后缀cut和不带后缀cut的文件的差异是什么呢？

**Comment by jiaq-liu** [comment]
> 你好！非常感谢你们提出了点云异常数据集。我有点问题想请教一下：1.我似乎并没有在数据集中看到文章中所说的incompleteness类型的异常，只有sink和bulge类型的异常？2.gt中带有后缀cut和不带后缀cut的文件的差异是什么呢？

你好！感谢对我们数据集的认可。incompleteness是指缺失类型的，对应数据集中就是sink类型的异常。后缀带有cut和不带cut的文件的差异则在于，带有cut的文件是从不带cut文件手工处理，切割点云使得点云边缘平滑得到的。
