### ISSUE TITLE
about setting environment

### ISSUE THREAD

**Issue by wangwei83** [M-3LAB/Real3D-AD#7]
When I excute code:

conda env create -f real3dad.yaml

there are some errors.

Can you supply any general or stepbystep information again? Thanks.

**Comment by wangwei83** [comment]
The error log is as follow,
``(base) wangwei-uestc@user-SYS-4029GP-TRT:/datadisk/wangwei/Real3D-AD$ conda env create -f real3dad.yaml
Collecting package metadata (repodata.json): / WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1                                                                                   done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 24.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



Downloading and Extracting Packages
readline-8.2         | 357 KB    | ###################################################################################################################### | 100% 
lcms2-2.12           | 312 KB    | ###################################################################################################################### | 100% 
nettle-3.7.3         | 809 KB    | ###################################################################################################################### | 100% 
libunistring-0.9.10  | 536 KB    | ###################################################################################################################### | 100% 
blas-1.0             | 1 KB      | ###################################################################################################################### | 100% 
libstdcxx-ng-11.2.0  | 4.7 MB    | ###################################################################################################################### | 100% 
ncurses-6.4          | 914 KB    | ###################################################################################################################### | 100% 
gmp-6.2.1            | 544 KB    | ###################################################################################################################### | 100% 
openh264-2.1.1       | 711 KB    | ###################################################################################################################### | 100% 
libpng-1.6.39        | 304 KB    | ###################################################################################################################### | 100% 
lame-3.100           | 323 KB    | ###################################################################################################################### | 100% 
gnutls-3.6.15        | 1.0 MB    | ###################################################################################################################### | 100% 
libgomp-11.2.0       | 474 KB    | ###################################################################################################################### | 100% 
freetype-2.12.1      | 626 KB    | ###################################################################################################################### | 100% 
libgcc-ng-11.2.0     | 5.3 MB    | ###################################################################################################################### | 100% 
_libgcc_mutex-0.1    | 2 KB      | ###################################################################################################################### | 100% 
_openmp_mutex-5.1    | 21 KB     | ###################################################################################################################### | 100% 
ld_impl_linux-64-2.3 | 654 KB    | ###################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/wangwei-uestc/anaconda3/envs/real3dad/bin/python', '-m', 'pip', 'install', '-U', '-r', '/datadisk/wangwei/Real3D-AD/condaenv.e2qv7vu1.requirements.txt']
Pip subprocess output:
Collecting absl-py==1.4.0
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
Collecting addict==2.4.0
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting asttokens==2.2.1
  Using cached asttokens-2.2.1-py2.py3-none-any.whl (26 kB)
Collecting backcall==0.2.0
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting cachetools==5.3.0
  Using cached cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Collecting charset-normalizer==3.1.0
  Using cached charset_normalizer-3.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (195 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting cmake==3.26.0
  Using cached cmake-3.26.0-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
Collecting comm==0.1.2
  Using cached comm-0.1.2-py3-none-any.whl (6.5 kB)
Collecting configargparse==1.5.3
  Using cached ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
Collecting contourpy==1.0.7
  Using cached contourpy-1.0.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (300 kB)
Collecting cycler==0.11.0
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting dash==2.9.1
  Using cached dash-2.9.1-py3-none-any.whl (10.2 MB)
Collecting dash-core-components==2.0.0
  Using cached dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-html-components==2.0.0
  Using cached dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-table==5.0.0
  Using cached dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Collecting debugpy==1.6.6
  Using cached debugpy-1.6.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting decorator==5.1.1
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting executing==1.2.0
  Using cached executing-1.2.0-py2.py3-none-any.whl (24 kB)
Collecting faiss-gpu==1.7.2
  Using cached faiss_gpu-1.7.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (85.5 MB)
Collecting fastjsonschema==2.16.3
  Using cached fastjsonschema-2.16.3-py3-none-any.whl (23 kB)
Collecting flask==2.2.3
  Using cached Flask-2.2.3-py3-none-any.whl (101 kB)
Collecting fonttools==4.39.2
  Using cached fonttools-4.39.2-py3-none-any.whl (1.0 MB)
Collecting google-auth==2.16.2
  Using cached google_auth-2.16.2-py2.py3-none-any.whl (177 kB)
Collecting google-auth-oauthlib==1.0.0
  Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
Collecting grpcio==1.51.3
  Using cached grpcio-1.51.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Collecting huggingface-hub==0.13.2
  Using cached huggingface_hub-0.13.2-py3-none-any.whl (199 kB)
Collecting idna==3.4
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting imageio==2.26.0
  Using cached imageio-2.26.0-py3-none-any.whl (3.4 MB)
Collecting importlib-metadata==6.1.0
  Using cached importlib_metadata-6.1.0-py3-none-any.whl (21 kB)
Collecting importlib-resources==5.12.0
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting ipykernel==6.21.3
  Using cached ipykernel-6.21.3-py3-none-any.whl (149 kB)
Collecting ipython==8.11.0
  Using cached ipython-8.11.0-py3-none-any.whl (793 kB)
Collecting ipywidgets==8.0.4
  Using cached ipywidgets-8.0.4-py3-none-any.whl (137 kB)
Collecting itsdangerous==2.1.2
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting jedi==0.18.2
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
Collecting jinja2==3.1.2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting joblib==1.2.0
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
Collecting jupyter-client==8.0.3
  Using cached jupyter_client-8.0.3-py3-none-any.whl (102 kB)
Collecting jupyter-core==5.3.0
  Using cached jupyter_core-5.3.0-py3-none-any.whl (93 kB)
Collecting jupyterlab-widgets==3.0.5
  Using cached jupyterlab_widgets-3.0.5-py3-none-any.whl (384 kB)
Collecting kiwisolver==1.4.4
  Using cached kiwisolver-1.4.4-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)

Pip subprocess error:
ERROR: Ignored the following versions that require a different python version: 1.2.0 Requires-Python >=3.9; 1.2.1 Requires-Python >=3.9; 1.2.1rc1 Requires-Python >=3.9; 8.13.1 Requires-Python >=3.9; 8.13.2 Requires-Python >=3.9; 8.14.0 Requires-Python >=3.9; 8.15.0 Requires-Python >=3.9; 8.16.0 Requires-Python >=3.9; 8.16.1 Requires-Python >=3.9; 8.17.0 Requires-Python >=3.9; 8.17.1 Requires-Python >=3.9; 8.17.2 Requires-Python >=3.9; 8.18.0 Requires-Python >=3.9; 8.18.1 Requires-Python >=3.9; 8.19.0 Requires-Python >=3.10; 8.20.0 Requires-Python >=3.10; 8.21.0 Requires-Python >=3.10; 8.22.0 Requires-Python >=3.10; 8.22.1 Requires-Python >=3.10; 8.22.2 Requires-Python >=3.10; 8.23.0 Requires-Python >=3.10; 8.24.0 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement knn-cuda==0.2 (from versions: none)
ERROR: No matching distribution found for knn-cuda==0.2
                                                                                                                                                               failed

CondaEnvException: Pip failed

(base) wangwei-uestc@user-SYS-4029GP-TRT:/datadisk/wangwei/Real3D-AD$

**Comment by jiaq-liu** [comment]
> When I excute code:
> 
> conda env create -f real3dad.yaml
> 
> there are some errors.
> 
> Can you supply any general or stepbystep again? Thanks.

The most import point is to install point2_ops_lib. I install it follow M3DM(https://github.com/nomewang/M3DM).
But I'm not sure how to install it well in different operation system. 
Here is a conda environment (https://drive.google.com/file/d/1NozIUAj84oMoa9eomZ6b-sZI032sv30r/view?usp=drive_link). Hope it can help you.
