### ISSUE TITLE
关于benchmark测试脚本的报错

### ISSUE THREAD

**Issue by lzd-1230** [M-3LAB/Real3D-AD#9]
作者您好, 在debian11下配好环境之后我运行start.sh中在相关地方出现报错

在main_patchcore_fpfh_raw.py等代码中concatenate时候会报错

`main_patchcore_fpfh_raw.py`
```
Traceback (most recent call last):
  File "main_patchcore_fpfh_raw.py", line 226, in <module>
    main() 
    ............
  File "main_patchcore_fpfh_raw.py", line 180, in run
    ap_mask = np.concatenate(np.asarray(masks_gt))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
```

`main_patchcore_pointmae.py`
```                                             
INFO:__main__:Computing evaluation metrics.
Traceback (most recent call last):
  File "main_patchcore_pointmae.py", line 210, in <module>
    main()
  .................
  File "main_patchcore_pointmae.py", line 156, in run
    ap_mask = np.concatenate(np.asarray(masks_gt))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
```

`main_reg3dad.py`
```                                                    
INFO:__main__:Computing evaluation metrics.
Traceback (most recent call last):
  File "main_reg3dad.py", line 236, in <module>
    main()
  ........
  File "main_reg3dad.py", line 180, in run
    ap_mask = np.concatenate(np.asarray(masks_gt))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
```

我修改的地方只有在第一次运行的时候找不到 pointmae_pretrain.pth, 然后我将下载下来的权重 pretrain.pth 改名成前者

**Comment by jiaq-liu** [comment]
> 作者您好, 在debian11下配好环境之后我运行start.sh中在相关地方出现报错
> 
> 在main_patchcore_fpfh_raw.py等代码中concatenate时候会报错
> 
> `main_patchcore_fpfh_raw.py`
> 
> ```
> Traceback (most recent call last):
>   File "main_patchcore_fpfh_raw.py", line 226, in <module>
>     main() 
>     ............
>   File "main_patchcore_fpfh_raw.py", line 180, in run
>     ap_mask = np.concatenate(np.asarray(masks_gt))
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
> ```
> 
> `main_patchcore_pointmae.py`
> 
> ```
> INFO:__main__:Computing evaluation metrics.
> Traceback (most recent call last):
>   File "main_patchcore_pointmae.py", line 210, in <module>
>     main()
>   .................
>   File "main_patchcore_pointmae.py", line 156, in run
>     ap_mask = np.concatenate(np.asarray(masks_gt))
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
> ```
> 
> `main_reg3dad.py`
> 
> ```
> INFO:__main__:Computing evaluation metrics.
> Traceback (most recent call last):
>   File "main_reg3dad.py", line 236, in <module>
>     main()
>   ........
>   File "main_reg3dad.py", line 180, in run
>     ap_mask = np.concatenate(np.asarray(masks_gt))
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (100,) + inhomogeneous part.
> ```
> 
> 我修改的地方只有在第一次运行的时候找不到 pointmae_pretrain.pth, 然后我将下载下来的权重 pretrain.pth 改名成前者

我没有用过debian环境，但看上去不是环境问题。(“这个错误通常是由于试图将一个包含多个元素的序列赋值给一个numpy数组的单个元素所引起的。numpy数组中的每个元素都应该是单个值，而不是多个值组成的序列。”)看上去像是读取文件格式的问题，是不是没有在代码中修改对应的数据集位置呢?或者可能需要单步调试一下，在line 153行"scores_xyz, segmentations_xyz, labels_gt, masks_gt = PatchCore.predict( test_loader )"里面看看是不是在predict的时候返回的结果出现了格式错误的情况。

**Comment by Guangyun-Xu** [comment]
我遇到了同样的问题，我系统是ubuntu20.04，cuda是11.8，pytorch 2.4.1
@shirowalker 可否提供一下您在什么系统下进行开发的，cuda版本是多少，real3dad.yaml导出时`conda env export` 可以加上` --no-builds`这个选项，否则只能在跟您一样的环境下创建虚拟环境。

**Comment by Guangyun-Xu** [comment]
将`ap_mask = np.concatenate(np.asarray(masks_gt))`改为`ap_mask = np.concatenate(np.asarray(masks_gt, dtype=object))`得到了解决

**Comment by jiaq-liu** [comment]
@Guangyun-Xu 不好意思没有留意到第一条消息。我的运行环境是centos/redhat的企业定制版os,现在已经无法访问到具体信息了。 cuda版本是11.3。看起来错误的主要问题可能是pytorch或numpy版本过高了。
